name: Cargo Build, Test, and Linting

on:
    push:
    pull_request:

env:
    CARGO_TERM_COLOR: always
    RUSTFLAGS: "-Dwarnings"

jobs:
    format:
        name: Check formatting
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: cachix/install-nix-action@v31
            - uses: Swatinem/rust-cache@v2
            - run: nix shell --run "cargo fmt --check"

    clippy:
        name: Run lints
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: cachix/install-nix-action@v31
            - uses: Swatinem/rust-cache@v2
            - run: nix shell --run "cargo clippy --all-targets --all-features"

    build_and_test:
        name: Build project and test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: cachix/install-nix-action@v31
            - uses: Swatinem/rust-cache@v2
            - run: nix shell --run "cargo test --verbose"

    build_release:
        name: Build project in release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: cachix/install-nix-action@v31
            - uses: Swatinem/rust-cache@v2
            - run: nix shell --run "cargo build --verbose --release"
            - name: Export executable
              uses: actions/upload-artifact@v4
              with:
                  name: waystart-${{ matrix.os }}
                  compression-level: 9
                  path: target/${{ matrix.target }}/release/waystart*

    clippy_release:
        name: Run lints in release mode
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: cachix/install-nix-action@v31
            - uses: Swatinem/rust-cache@v2
            - run: nix shell --run "cargo clippy --release --all-targets --all-features"
